name: Docker Deploy  Incognito Index

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} 
          #uses:docker/login-action@v1


      - name: Build the Docker Image
        run: docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/incognito-deploy-index:${{ github.sha }} . 


      - name: Docker Push Image
        run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/incognito-deploy-index:${{ github.sha }}





      #uses: docker/build-push0action@v2
      #with: 
        #context: .
        #push: true
        #tags: ruslan8424/Deploy_incognito:${{ github.sha }}

    #- name: Test Image # check if the image was created, for test purposes
    # run: docker images 



      - name: Deploy to EC2 instance 
        uses: ruslan8424/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }} 
          script:
            docker stop incognito-deploy-index || true
            docker rm incognito-deploy-index || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/incognito-deploy-index:${{ github.sha }}
            docker run -d name incognito-deploy-index -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/incognito-deploy-index:${{ github.sha }}
